version: '2'

services:

  cartpole-sota-napping:
    # The volume we mount determines which config files will be available to the services.
    volumes:
      - ./configs/partial:/aiq-sail-on/config:rw
      - ./logs:/aiq-sail-on/logs:rw
    build:
      context: .
      dockerfile: Dockerfile-NAPPING-DQN
    command: python -u SOTA-cartpole-napping.py --config=config/demo-client.config --printout --logfile=logs/log.txt
